apiVersion: v1
kind: Pod
metadata:
  name: client-on-ovn-worker
  namespace: default
  labels:
    pod-name: client-on-ovn-worker
spec:
  containers:
  - name: client
    image: docker.io/centos/tools:latest
    command:
      - /sbin/init
  nodeSelector:
    kubernetes.io/hostname: ovn-worker

