apiVersion: v1
kind: Pod
metadata:
  name: server-on-ovn-worker2
  namespace: default
  labels:
    pod-name: server-on-ovn-worker2
spec:
  containers:
  - name: web-server
    image: quay.io/itssurya/dev-images:workshop-webserver-final
  ports:
    - containerPort: 80
  command:
    - /sbin/init
  nodeSelector:
    kubernetes.io/hostname: ovn-worker2

